import type { Vehicle } from './types'

export const VEHICLES: Vehicle[] = [
  // ═══════════════════════════════ CARS ════════════════════════════════════

  {
    id: 'maruti-alto-k10',
    name: 'Maruti Suzuki Alto K10',
    brand: 'Maruti Suzuki',
    category: 'car',
    fuelType: 'petrol',
    startingPrice: 399000,
    monthlyOwnership: 9500,
    imageEmoji: '🚗',
    imageGradient: 'from-blue-400 to-blue-600',
    specs: {
      mileage: 24.39,
      engineCC: 998,
      seatingCapacity: 5,
      bootSpaceLitres: 214,
      lengthMm: 3530,
      widthMm: 1490,
      safetyStars: null,
      hasAutoTransmission: true,
    },
    lucknow: {
      groundClearanceMm: 160,
      serviceCentersTotal: 18,
      serviceCentersByZone: { gomti_nagar: 6, alambagh: 5, rajajipuram: 4, outskirts: 3 },
      evChargerCompatible: false,
      cngFactoryFitted: true,
      waitingPeriodWeeks: 1,
      sparePartsAvailability: 'excellent',
      commonIssues: [
        'Ground clearance of 160mm causes underbody scraping on pothole-heavy Rajajipuram / Chowk roads',
        'AC feels underpowered during Lucknow peak summers (42°C+) — budget for AC regas every 2 seasons',
      ],
      lastUpdated: '2025-01-15',
    },
  },

  {
    id: 'maruti-swift',
    name: 'Maruti Suzuki Swift',
    brand: 'Maruti Suzuki',
    category: 'car',
    fuelType: 'petrol',
    startingPrice: 649000,
    monthlyOwnership: 15500,
    imageEmoji: '🚗',
    imageGradient: 'from-red-400 to-red-600',
    specs: {
      mileage: 23.76,
      engineCC: 1197,
      seatingCapacity: 5,
      bootSpaceLitres: 268,
      lengthMm: 3845,
      widthMm: 1735,
      safetyStars: null,
      hasAutoTransmission: true,
    },
    lucknow: {
      groundClearanceMm: 163,
      serviceCentersTotal: 18,
      serviceCentersByZone: { gomti_nagar: 6, alambagh: 5, rajajipuram: 4, outskirts: 3 },
      evChargerCompatible: false,
      cngFactoryFitted: false,
      waitingPeriodWeeks: 3,
      sparePartsAvailability: 'excellent',
      commonIssues: [
        'Ground clearance of 163mm limits use on heavily-damaged Rajajipuram / Chowk roads — scraping occurs',
        'No factory CNG variant — aftermarket CNG kit voids manufacturer warranty',
      ],
      lastUpdated: '2025-01-15',
    },
  },

  {
    id: 'maruti-wagon-r-cng',
    name: 'Maruti Suzuki WagonR CNG',
    brand: 'Maruti Suzuki',
    category: 'car',
    fuelType: 'cng',
    startingPrice: 699000,
    monthlyOwnership: 13000,
    imageEmoji: '🚗',
    imageGradient: 'from-green-400 to-green-600',
    specs: {
      mileage: 34.05,
      engineCC: 1197,
      seatingCapacity: 5,
      bootSpaceLitres: 341,
      lengthMm: 3655,
      widthMm: 1620,
      safetyStars: null,
      hasAutoTransmission: false,
    },
    lucknow: {
      groundClearanceMm: 175,
      serviceCentersTotal: 18,
      serviceCentersByZone: { gomti_nagar: 6, alambagh: 5, rajajipuram: 4, outskirts: 3 },
      evChargerCompatible: false,
      cngFactoryFitted: true,
      waitingPeriodWeeks: 6,
      sparePartsAvailability: 'excellent',
      commonIssues: [
        'CNG stations in Rajajipuram zone are often crowded — plan 15 extra minutes on refill days',
        'Boot space reduced by ~30 litres due to CNG cylinder; carrying festival luggage is tighter',
      ],
      lastUpdated: '2025-01-15',
    },
  },

  {
    id: 'maruti-ertiga',
    name: 'Maruti Suzuki Ertiga',
    brand: 'Maruti Suzuki',
    category: 'car',
    fuelType: 'petrol',
    startingPrice: 869000,
    monthlyOwnership: 22000,
    imageEmoji: '🚐',
    imageGradient: 'from-violet-400 to-violet-600',
    specs: {
      mileage: 20.51,
      engineCC: 1462,
      seatingCapacity: 7,
      bootSpaceLitres: 209,
      lengthMm: 4395,
      widthMm: 1735,
      safetyStars: null,
      hasAutoTransmission: true,
    },
    lucknow: {
      groundClearanceMm: 180,
      serviceCentersTotal: 18,
      serviceCentersByZone: { gomti_nagar: 6, alambagh: 5, rajajipuram: 4, outskirts: 3 },
      evChargerCompatible: false,
      cngFactoryFitted: true,
      waitingPeriodWeeks: 4,
      sparePartsAvailability: 'excellent',
      commonIssues: [
        '7-seater bulk makes parking in tight Lucknow markets (Aminabad, Hazratganj lanes) challenging',
        'Petrol variant less economical for daily commutes; CNG variant costs ₹70K more upfront',
      ],
      lastUpdated: '2025-01-15',
    },
  },

  {
    id: 'maruti-brezza',
    name: 'Maruti Suzuki Brezza',
    brand: 'Maruti Suzuki',
    category: 'car',
    fuelType: 'petrol',
    startingPrice: 834000,
    monthlyOwnership: 21000,
    imageEmoji: '🚙',
    imageGradient: 'from-orange-400 to-orange-600',
    specs: {
      mileage: 19.89,
      engineCC: 1462,
      seatingCapacity: 5,
      bootSpaceLitres: 328,
      lengthMm: 3995,
      widthMm: 1790,
      safetyStars: null,
      hasAutoTransmission: true,
    },
    lucknow: {
      groundClearanceMm: 185,
      serviceCentersTotal: 18,
      serviceCentersByZone: { gomti_nagar: 6, alambagh: 5, rajajipuram: 4, outskirts: 3 },
      evChargerCompatible: false,
      cngFactoryFitted: false,
      waitingPeriodWeeks: 8,
      sparePartsAvailability: 'excellent',
      commonIssues: [
        'Current Lucknow dealership waiting period is 8 weeks — book early, especially for red/white colours',
        'No CNG or diesel option; petrol-only limits running-cost optimisation for high-mileage users',
      ],
      lastUpdated: '2025-01-15',
    },
  },

  {
    id: 'tata-nexon',
    name: 'Tata Nexon',
    brand: 'Tata Motors',
    category: 'car',
    fuelType: 'petrol',
    startingPrice: 810000,
    monthlyOwnership: 21500,
    imageEmoji: '🚙',
    imageGradient: 'from-blue-600 to-indigo-700',
    specs: {
      mileage: 17.01,
      engineCC: 1199,
      seatingCapacity: 5,
      bootSpaceLitres: 350,
      lengthMm: 3994,
      widthMm: 1811,
      safetyStars: 5,
      hasAutoTransmission: true,
    },
    lucknow: {
      groundClearanceMm: 209,
      serviceCentersTotal: 7,
      serviceCentersByZone: { gomti_nagar: 3, alambagh: 2, rajajipuram: 1, outskirts: 1 },
      evChargerCompatible: false,
      cngFactoryFitted: false,
      waitingPeriodWeeks: 8,
      sparePartsAvailability: 'good',
      commonIssues: [
        'Only 7 authorized Tata service centers in Lucknow — peak season appointments book 1–2 weeks ahead',
        'No Tata service center east of Gomti river — Rajajipuram residents drive 12–15km for warranty work',
      ],
      lastUpdated: '2025-01-15',
    },
  },

  {
    id: 'hyundai-creta',
    name: 'Hyundai Creta',
    brand: 'Hyundai',
    category: 'car',
    fuelType: 'petrol',
    startingPrice: 1100000,
    monthlyOwnership: 28500,
    imageEmoji: '🚙',
    imageGradient: 'from-sky-500 to-blue-700',
    specs: {
      mileage: 16.8,
      engineCC: 1497,
      seatingCapacity: 5,
      bootSpaceLitres: 433,
      lengthMm: 4300,
      widthMm: 1790,
      safetyStars: 5,
      hasAutoTransmission: true,
    },
    lucknow: {
      groundClearanceMm: 190,
      serviceCentersTotal: 9,
      serviceCentersByZone: { gomti_nagar: 4, alambagh: 2, rajajipuram: 2, outskirts: 1 },
      evChargerCompatible: false,
      cngFactoryFitted: false,
      waitingPeriodWeeks: 12,
      sparePartsAvailability: 'good',
      commonIssues: [
        '12-week waiting period at Lucknow Hyundai dealerships for popular colours — plan purchases early',
        'AC draws heavy power in 42°C+ Lucknow summers; real-world mileage drops to 12–13 km/l in June',
      ],
      lastUpdated: '2025-01-15',
    },
  },

  {
    id: 'honda-city',
    name: 'Honda City 5th Gen',
    brand: 'Honda',
    category: 'car',
    fuelType: 'petrol',
    startingPrice: 1177000,
    monthlyOwnership: 30000,
    imageEmoji: '🚗',
    imageGradient: 'from-slate-500 to-slate-700',
    specs: {
      mileage: 17.8,
      engineCC: 1498,
      seatingCapacity: 5,
      bootSpaceLitres: 506,
      lengthMm: 4549,
      widthMm: 1748,
      safetyStars: null,
      hasAutoTransmission: true,
    },
    lucknow: {
      groundClearanceMm: 165,
      serviceCentersTotal: 6,
      serviceCentersByZone: { gomti_nagar: 3, alambagh: 2, rajajipuram: 1, outskirts: 0 },
      evChargerCompatible: false,
      cngFactoryFitted: false,
      waitingPeriodWeeks: 4,
      sparePartsAvailability: 'fair',
      commonIssues: [
        'Ground clearance of 165mm and sedan body causes scraping on monsoon-flooded Lucknow underpasses',
        'No authorized Honda service center east of Gomti river — 15+ km drive for Rajajipuram residents',
      ],
      lastUpdated: '2025-01-15',
    },
  },

  // ═══════════════════════════════ MOTORCYCLES ══════════════════════════════

  {
    id: 'hero-splendor-plus',
    name: 'Hero Splendor Plus',
    brand: 'Hero',
    category: 'motorcycle',
    fuelType: 'petrol',
    startingPrice: 77000,
    monthlyOwnership: 4800,
    imageEmoji: '🏍️',
    imageGradient: 'from-red-500 to-rose-700',
    specs: {
      mileage: 60,
      engineCC: 97.2,
      seatingCapacity: 2,
      bootSpaceLitres: 0,
      lengthMm: 1980,
      widthMm: 720,
      safetyStars: null,
      hasAutoTransmission: false,
    },
    lucknow: {
      groundClearanceMm: 165,
      serviceCentersTotal: 22,
      serviceCentersByZone: { gomti_nagar: 5, alambagh: 6, rajajipuram: 6, outskirts: 5 },
      evChargerCompatible: false,
      cngFactoryFitted: false,
      waitingPeriodWeeks: 0,
      sparePartsAvailability: 'excellent',
      commonIssues: [
        '97cc engine struggles on Lucknow–Kanpur highway at sustained 90 km/h — plan for longer travel times',
        'Base variant has drum brakes only — strongly recommend disc brake variant for Lucknow urban safety',
      ],
      lastUpdated: '2025-01-15',
    },
  },

  {
    id: 'royal-enfield-meteor-350',
    name: 'Royal Enfield Meteor 350',
    brand: 'Royal Enfield',
    category: 'motorcycle',
    fuelType: 'petrol',
    startingPrice: 221000,
    monthlyOwnership: 8500,
    imageEmoji: '🏍️',
    imageGradient: 'from-amber-700 to-yellow-900',
    specs: {
      mileage: 36,
      engineCC: 349,
      seatingCapacity: 2,
      bootSpaceLitres: 0,
      lengthMm: 2160,
      widthMm: 855,
      safetyStars: null,
      hasAutoTransmission: false,
    },
    lucknow: {
      groundClearanceMm: 170,
      serviceCentersTotal: 5,
      serviceCentersByZone: { gomti_nagar: 2, alambagh: 1, rajajipuram: 1, outskirts: 1 },
      evChargerCompatible: false,
      cngFactoryFitted: false,
      waitingPeriodWeeks: 6,
      sparePartsAvailability: 'good',
      commonIssues: [
        'The single Gomti Nagar RE dealership has service appointments stretched to 8–10 days in peak months',
        'Mild vibrations felt at 80+ km/h on rough Lucknow outskirts roads by some riders on long runs',
      ],
      lastUpdated: '2025-01-15',
    },
  },

  {
    id: 'tvs-apache-rtr-160',
    name: 'TVS Apache RTR 160 4V',
    brand: 'TVS',
    category: 'motorcycle',
    fuelType: 'petrol',
    startingPrice: 115000,
    monthlyOwnership: 6500,
    imageEmoji: '🏍️',
    imageGradient: 'from-gray-700 to-gray-900',
    specs: {
      mileage: 45,
      engineCC: 159.7,
      seatingCapacity: 2,
      bootSpaceLitres: 0,
      lengthMm: 2085,
      widthMm: 790,
      safetyStars: null,
      hasAutoTransmission: false,
    },
    lucknow: {
      groundClearanceMm: 180,
      serviceCentersTotal: 10,
      serviceCentersByZone: { gomti_nagar: 3, alambagh: 3, rajajipuram: 2, outskirts: 2 },
      evChargerCompatible: false,
      cngFactoryFitted: false,
      waitingPeriodWeeks: 2,
      sparePartsAvailability: 'good',
      commonIssues: [
        'Sporty, forward-leaning riding position becomes uncomfortable on 45+ minute bumpy Lucknow commutes',
        'Base variant lacks Bluetooth connectivity; 4V variant with SmartXonnect adds ₹10K to price',
      ],
      lastUpdated: '2025-01-15',
    },
  },

  // ═══════════════════════════════ SCOOTIES ═════════════════════════════════

  {
    id: 'honda-activa-125',
    name: 'Honda Activa 125 H-Smart',
    brand: 'Honda',
    category: 'scooty',
    fuelType: 'petrol',
    startingPrice: 89000,
    monthlyOwnership: 5500,
    imageEmoji: '🛵',
    imageGradient: 'from-red-400 to-orange-500',
    specs: {
      mileage: 60,
      engineCC: 123.92,
      seatingCapacity: 2,
      bootSpaceLitres: 18,
      lengthMm: 1868,
      widthMm: 713,
      safetyStars: null,
      hasAutoTransmission: true,
    },
    lucknow: {
      groundClearanceMm: 171,
      serviceCentersTotal: 14,
      serviceCentersByZone: { gomti_nagar: 4, alambagh: 4, rajajipuram: 4, outskirts: 2 },
      evChargerCompatible: false,
      cngFactoryFitted: false,
      waitingPeriodWeeks: 1,
      sparePartsAvailability: 'excellent',
      commonIssues: [
        '18L under-seat storage cannot carry a full office bag — a rear carrier accessory (₹500) is essential',
        'CBS-only braking (no ABS) — stopping distances on wet Lucknow monsoon roads are longer than ABS bikes',
      ],
      lastUpdated: '2025-01-15',
    },
  },

  {
    id: 'tvs-jupiter-classic',
    name: 'TVS Jupiter Classic',
    brand: 'TVS',
    category: 'scooty',
    fuelType: 'petrol',
    startingPrice: 79000,
    monthlyOwnership: 5200,
    imageEmoji: '🛵',
    imageGradient: 'from-yellow-400 to-amber-600',
    specs: {
      mileage: 50,
      engineCC: 109.7,
      seatingCapacity: 2,
      bootSpaceLitres: 22,
      lengthMm: 1845,
      widthMm: 705,
      safetyStars: null,
      hasAutoTransmission: true,
    },
    lucknow: {
      groundClearanceMm: 160,
      serviceCentersTotal: 11,
      serviceCentersByZone: { gomti_nagar: 3, alambagh: 3, rajajipuram: 3, outskirts: 2 },
      evChargerCompatible: false,
      cngFactoryFitted: false,
      waitingPeriodWeeks: 1,
      sparePartsAvailability: 'good',
      commonIssues: [
        'Ground clearance of 160mm — Lucknow inner zones (Chowk, Aminabad) with severe potholes will cause scraping',
        'TVS service quality in Lucknow varies by workshop — check Google reviews before booking your nearest outlet',
      ],
      lastUpdated: '2025-01-15',
    },
  },
]

export function getVehicleById(id: string): Vehicle | undefined {
  return VEHICLES.find((v) => v.id === id)
}
